SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Space Invaders"

SHIP_RADIUS = 25
SHIP_LIVES = 5

BULLET_RADIUS = 25
BULLET_SPEED = 5
BULLET_LIFE = 160

ALIENS = 6
ALIEN_RADIUS = 25
ALIEN_SPEED = 8
ALIEN_SPEED_Y = -.2
