SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Space Invaders"

SHIP_RADIUS = 25
SHIP_LIVES = 3

BULLET_RADIUS = 25
BULLET_SPEED = 3
BULLET_LIFE = 160

ALIENS = 8
ALIEN_RADIUS = 25
ALIEN_SPEED = 10
ALIEN_SPEED_Y = -.5
